// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazor.Cakes.Data;

#nullable disable

namespace MudBlazor.Cakes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MudBlazor.Cakes.Data.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Cakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bolo de banana",
                            ImageUrl = "Images/bolo_banana.jpg",
                            Name = "Bolo de banana",
                            Price = 23.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bolo de brigadeiro",
                            ImageUrl = "Images/bolo_brigadeiro.jpg",
                            Name = "Bolo de Brigadeiro",
                            Price = 31.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bolo de Chocolate",
                            ImageUrl = "Images/bolo_chocolate.jpg",
                            Name = "Bolo de Chocolate",
                            Price = 41.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bolo de laranja",
                            ImageUrl = "Images/bolo_laranja.webp",
                            Name = "Bolo de Laranja",
                            Price = 35.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
